// lib/scanner/protocol-generator.ts
// Auto-generates agentic commerce protocol files from scan data.

import type { ScanResult, ProtocolFile, ProtocolFiles } from '../types';

function extractMerchantName(result: ScanResult): string {
  let domain = 'Your Store';
  try { domain = new URL(result.normalizedUrl).hostname.replace('www.', ''); } catch { /* */ }
  return domain;
}

function extractDescription(result: ScanResult): string {
  return `Shop at ${extractMerchantName(result)} — discover our full product catalog.`;
}

function generateUcp(result: ScanResult): ProtocolFile {
  const name = extractMerchantName(result);
  const hasReviews = result.categories.structuredData.percentage >= 50;
  const platform = result.metadata.platform;

  const ucp = {
    version: '1.0',
    merchant: {
      name,
      url: result.normalizedUrl,
      description: extractDescription(result),
      logo: `${result.normalizedUrl}/logo.png`,
    },
    capabilities: {
      product_search: true,
      product_details: true,
      pricing: true,
      availability: true,
      reviews: hasReviews,
      checkout: false,
    },
    endpoints: {
      products: `${result.normalizedUrl}/api/products`,
      search: `${result.normalizedUrl}/api/search`,
      product_detail: `${result.normalizedUrl}/api/products/{id}`,
    },
    supported_agents: ['*'],
    rate_limits: {
      requests_per_minute: 60,
      requests_per_day: 10000,
    },
  };

  let instructions = 'Upload this file to your site root at /.well-known/ucp.json';
  if (platform === 'shopify') {
    instructions = 'Shopify: Create a page template that serves this JSON, or use a proxy route in your theme.';
  } else if (platform === 'woocommerce') {
    instructions = 'WooCommerce: Place this file in your WordPress root directory under .well-known/ucp.json, or add a rewrite rule.';
  }

  return {
    filename: 'ucp.json',
    path: '/.well-known/ucp.json',
    content: JSON.stringify(ucp, null, 2),
    description: 'Universal Commerce Protocol manifest — tells AI agents what your store offers and how to interact with it.',
    deployInstructions: instructions,
  };
}

function generateMcp(result: ScanResult): ProtocolFile {
  const name = extractMerchantName(result);
  const platform = result.metadata.platform;

  const mcp = {
    schema_version: '1.0',
    name,
    description: extractDescription(result),
    tools: [
      {
        name: 'search_products',
        description: `Search products in ${name}'s catalog`,
        parameters: {
          query: { type: 'string', description: 'Search query' },
          category: { type: 'string', description: 'Product category' },
          max_price: { type: 'number', description: 'Maximum price filter' },
        },
      },
      {
        name: 'get_product',
        description: 'Get detailed product information by ID or SKU',
        parameters: {
          product_id: { type: 'string', description: 'Product ID or SKU' },
        },
      },
      {
        name: 'check_availability',
        description: 'Check if a product is in stock',
        parameters: {
          product_id: { type: 'string', description: 'Product ID or SKU' },
        },
      },
    ],
    resources: [
      {
        name: 'product_catalog',
        description: 'Full product catalog via sitemap',
        uri: `${result.normalizedUrl}/sitemap.xml`,
      },
    ],
  };

  let instructions = 'Upload this file to your site root at /.well-known/mcp.json';
  if (platform === 'shopify') {
    instructions = 'Shopify: Add this as a JSON asset or serve via a proxy route. You will also need to implement the tool endpoints.';
  }

  return {
    filename: 'mcp.json',
    path: '/.well-known/mcp.json',
    content: JSON.stringify(mcp, null, 2),
    description: 'Model Context Protocol manifest — enables AI models to interact with your store programmatically.',
    deployInstructions: instructions,
  };
}

function generateRobotsTxt(result: ScanResult): ProtocolFile {
  const sitemapUrl = `${result.normalizedUrl}/sitemap.xml`;

  const content = `# AI Shopping Agent Access — Generated by AgentProof
# Last updated: ${new Date().toISOString().split('T')[0]}

User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Amazonbot
Allow: /

User-agent: *
Allow: /
Disallow: /admin/
Disallow: /cart/
Disallow: /checkout/
Disallow: /account/
Disallow: /search?*

Sitemap: ${sitemapUrl}
`;

  return {
    filename: 'robots.txt',
    path: '/robots.txt',
    content,
    description: 'Optimized robots.txt that allows all major AI shopping agent crawlers.',
    deployInstructions: result.metadata.platform === 'shopify'
      ? 'Shopify: Go to Online Store > Themes > Edit Code > robots.txt.liquid. Replace the content.'
      : 'Replace (or merge with) your existing robots.txt in the site root directory.',
  };
}

export function generateProtocolFiles(result: ScanResult): ProtocolFiles {
  return {
    ucp: generateUcp(result),
    mcp: generateMcp(result),
    robotsTxt: generateRobotsTxt(result),
  };
}
